function [ reel ] = raw2movie( basename, z_norm, decades )
%raw2movie creates a movie from binary data files generated by FDTDcore
%basename: root of file names
%z_norm: normalization value (default 1)
%decades: logarithmic scaling factor (default 3)
%reel: movie object, can be used in movie(reel, 10) for example

if nargin < 3, decades = 3; end
if nargin < 2, z_norm = 1.0; end

%initial frame
frame = 0;
filename = sprintf('%s.%d', basename, frame);
fid = fopen(filename, 'rb'); %opens binary file

if fid == -1
    error(['raw2movie:first frame not found', filename]);
end

%loop through all files
while fid ~= -1
    size_x = fread(fid, 1, 'single');
    size_y = fread(fid, 1, 'single');
    
    data = reshape(fread(fid, size_x * size_y, 'single'), size_x, size_y);
    if decades ~= 0
        pcolor(log10(abs((data + realmin) / z_norm)))
        shading flat
        axis equal
        axis([1 size_x 1 size_y])
        caxis([-decades 0])
        colorbar
    else
         pcolor(abs((data + realmin) / z_norm))
        shading flat
        axis equal
        axis([1 size_x 1 size_y])
        caxis([0 1])
        colorbar
    end
    
    reel(frame+1) = getframe;
    
    frame = frame + 1;
    filename = sprintf('%s.%d', basename, frame);
    fid = fopen(filename, 'rb'); %opens binary file
end

end

